import Link from "next/link";
import { Metadata } from "next";

const DICT: Record<string, any> = {
  id: {
    title: "Syarat Layanan",
    lastUpdated: "Terakhir Diperbarui: Mei 2026",
    content: [
      { h: "1. Penerimaan Syarat", p: "Dengan mengakses dan menggunakan PersonaHub, Anda menyetujui untuk terikat oleh Syarat Layanan ini. Jika Anda tidak setuju, mohon untuk tidak menggunakan layanan kami." },
      { h: "2. Sifat Layanan (Disclaimer Legal)", p: "PersonaHub menyediakan alat analisis kepribadian, primbon, kartu takdir, dan astrologi murni untuk tujuan HIBURAN dan REFLEKSI DIRI. Layanan kami bukan pengganti saran medis, psikologis, atau profesional bersertifikat. Segala keputusan hidup berdasarkan hasil tes adalah tanggung jawab Anda sepenuhnya." },
      { h: "3. Hak Kekayaan Intelektual", p: "Seluruh konten, algoritma, desain antarmuka, dan teks di situs ini adalah milik PersonaHub. Dilarang menyalin, mereproduksi, atau mendistribusikan ulang kode atau aset tanpa izin tertulis." },
      { h: "4. Batasan Tanggung Jawab", p: "PersonaHub tidak bertanggung jawab atas segala kerugian langsung maupun tidak langsung yang timbul akibat penggunaan, interpretasi, atau ketergantungan pada informasi dan hasil tes yang dihasilkan oleh platform kami." },
    ]
  },
  en: {
    title: "Terms of Service",
    lastUpdated: "Last Updated: May 2026",
    content: [
      { h: "1. Acceptance of Terms", p: "By accessing and using PersonaHub, you agree to be bound by these Terms of Service. If you disagree, please do not use our services." },
      { h: "2. Nature of Service (Disclaimer)", p: "PersonaHub provides personality analysis, destiny cards, and astrology tools purely for ENTERTAINMENT and SELF-REFLECTION. Our services are not a substitute for certified medical, psychological, or professional advice. All life decisions based on test results are entirely your responsibility." },
      { h: "3. Intellectual Property", p: "All content, algorithms, UI design, and text on this site are the property of PersonaHub. Copying, reproducing, or redistributing code or assets without written permission is prohibited." },
      { h: "4. Limitation of Liability", p: "PersonaHub is not liable for any direct or indirect damages arising from the use, interpretation, or reliance on the information and test results generated by our platform." },
    ]
  },
  es: {
    title: "Términos de Servicio",
    lastUpdated: "Última Actualización: Mayo 2026",
    content: [
      { h: "1. Aceptación de Términos", p: "Al acceder y usar PersonaHub, acepta estar sujeto a estos Términos de Servicio. Si no está de acuerdo, no use nuestros servicios." },
      { h: "2. Naturaleza del Servicio (Descargo)", p: "PersonaHub proporciona análisis de personalidad y astrología puramente para ENTRETENIMIENTO y AUTORREFLEXIÓN. Nuestros servicios no sustituyen el consejo médico o psicológico certificado. Todas las decisiones de vida basadas en los resultados son su responsabilidad." },
      { h: "3. Propiedad Intelectual", p: "Todo el contenido, algoritmos, diseño de interfaz y texto en este sitio son propiedad de PersonaHub. Queda prohibida la copia o redistribución sin permiso." },
      { h: "4. Limitación de Responsabilidad", p: "PersonaHub no se hace responsable de los daños directos o indirectos que surjan del uso o interpretación de la información generada por nuestra plataforma." },
    ]
  }
};

export async function generateMetadata({ params }: { params: { lang: string } }): Promise<Metadata> {
  const lang = params.lang || "id";
  const t = DICT[lang] || DICT.id;
  return { title: `${t.title} | PersonaHub` };
}

export default function TermsOfServicePage({ params }: { params: { lang: string } }) {
  const lang = params.lang || "id";
  const data = DICT[lang] || DICT.id;

  return (
    <main className="min-h-screen bg-slate-950 text-slate-300 py-20 px-4">
      <div className="max-w-3xl mx-auto bg-slate-900/50 border border-white/10 p-8 md:p-12 rounded-3xl backdrop-blur-sm shadow-xl">
        <h1 className="text-3xl md:text-5xl font-black text-white mb-4">{data.title}</h1>
        <p className="text-purple-400 text-sm font-bold tracking-widest uppercase mb-10">{data.lastUpdated}</p>
        
        <div className="space-y-8">
          {data.content.map((section: any, idx: number) => (
            <section key={idx}>
              <h2 className="text-xl font-bold text-slate-100 mb-3">{section.h}</h2>
              <p className="text-slate-400 leading-relaxed text-sm md:text-base">{section.p}</p>
            </section>
          ))}
        </div>
      </div>
    </main>
  );
}